# Generated by Django 3.1.6 on 2021-02-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='author name')),
                ('genre', models.CharField(max_length=50, null=True, verbose_name='book genre')),
                ('book_name', models.CharField(max_length=50, verbose_name='book name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='book description')),
            ],
        ),
    ]
