# Generated by Django 3.1.6 on 2021-02-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Author name')),
                ('book_name', models.CharField(max_length=50, verbose_name='Book name')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50, null=True, verbose_name='style book')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='book description')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='book.author', verbose_name='Author')),
            ],
        ),
    ]
