# Generated by Django 3.1.6 on 2021-02-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='book.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='pk'),
        ),
    ]
