# Generated by Django 3.1.6 on 2021-02-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, null=True, verbose_name='book genre')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='book description')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='book.author', verbose_name='Author')),
            ],
        ),
    ]
