# Generated by Django 3.1.6 on 2021-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210203_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='style',
            field=models.CharField(max_length=50, null=True, verbose_name='style book'),
        ),
    ]
