# Generated by Django 3.1.6 on 2021-02-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210203_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='Author',
        ),
    ]
