# Generated by Django 3.1.7 on 2021-02-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izdatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izdatel_name', models.CharField(max_length=50, verbose_name='Name of Izdatel')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='izdatel', to='book.author', verbose_name='Author')),
            ],
        ),
    ]
